sudo: required
services:
  - docker

language: python

python:
#  - 3.5.2
#  - 3.5
  - 3.6
  - 3.6-dev
  - 3.7
  - nightly

matrix:
  allow_failures:
    - python: '3.6-dev'
    - python: '3.7'
    - python: 'nightly'

cache:
  directories:
  - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install --upgrade pip wheel
  - pip install --upgrade setuptools
  - pip install flake8
  - pip install pytest pytest-cov pytest-asyncio codecov uvloop -e .

script:
  - flake8 aiosip examples tests
  - py.test --cov=aiosip --cov-report=term --cov-report=html --cov-append --loop pyloop,uvloop tests

after_success:
  - codecov
